kind: Deployment
apiVersion: apps/v1
metadata:
  name: arecgisv2-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arecgisv2-backend
  template:
    metadata:
      labels:
        app: arecgisv2-backend
    spec:
      containers:
      - name: arecgisv2-backend
        image: dextiee/arecgis-v2:v3
        ports:
        - containerPort: 3000
      dnsPolicy: Default