apiVersion: v1
kind: Service
metadata:
  name: file-api-service
  labels:
    app: file-api
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31300
  selector:
    app: file-api