kind: Deployment
apiVersion: apps/v1
metadata:
  name: umans-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: umans-frontend
  template:
    metadata:
      labels:
        app: umans-frontend
    spec:
      containers:
      - name: umans-frontend
        image: raevillena21/umans-static:v1.0.4
        ports:
        - containerPort: 80