apiVersion: v1
kind: Service
metadata:
  name: umans-backend-service
  labels:
    app: umans-backend
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    nodePort: 31124
  selector:
    app: umans-backend