apiVersion: v1
kind: Service
metadata:
  name: umans-frontend-service
  labels:
    app: umans-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31125
  selector:
    app: umans-frontend