kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: kowbee/arec-client:v1
        ports:
        - containerPort: 80