apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31123
  selector:
    app: react