kind: Deployment
apiVersion: apps/v1
metadata:
  name: solarcalc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solarcalc-backend
  template:
    metadata:
      labels:
        app: solarcalc-backend
    spec:
      containers:
      - name: solarcalc-backend
        image: juliusrarogal/solarcalc-backend:v1
        ports:
        - containerPort: 4001
        env:
        # TODO: replace with the real values from ./my-express-web-server/.env
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4001"
---
apiVersion: v1
kind: Service
metadata:
  name: solarcalc-backend-service
  labels:
    app: solarcalc-backend
spec:
  type: LoadBalancer
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP
    nodePort: 31126
  selector:
    app: solarcalc-backend
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: solarcalc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solarcalc-frontend
  template:
    metadata:
      labels:
        app: solarcalc-frontend
    spec:
      containers:
      - name: solarcalc-frontend
        image: juliusrarogal/solarcalc-frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: solarcalc-frontend-service
  labels:
    app: solarcalc-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    nodePort: 31127
  selector:
    app: solarcalc-frontend
